OpenSourcePolitics/decidim-lyon

OVERLOADS.md
app/cells/decidim/proposals/proposal_m_cell.rb
config/i18n-tasks.yml

Disable cells proposals caching since it isn't reliable because of Participatory Processes show view. 
A user navigating first on PP show view can cache a different format of cells and then keep it in cache in index view.

Disable proposals cells caching

---

app/assets/config/manifest.js
app/assets/javascripts/application.js
app/assets/javascripts/decidim/proposals/add_proposal.js.es6
app/forms/decidim/proposals/proposal_form.rb
app/views/decidim/proposals/collaborative_drafts/_edit_form_fields.html.erb
app/views/decidim/proposals/proposals/_edit_form_fields.html.erb
config/i18n-tasks.yml
config/locales/en.yml
config/locales/fr.yml
spec/forms/decidim/proposals/proposal_form_spec.rb
spec/shared/proposal_form_examples.rb
spec/spec_helper.rb
spec/system/proposal_fields_spec.rb

*Mettre à la ligne et en italique le texte “Attention : le déposant s’engage à posséder les droits de diffusion de l’image”*

[Feature] - customize proposal form

---

app/cells/decidim/proposals/proposal_m_cell.rb

There is a caching troubleshooting when user navigates between participatory process show view and proposals index.
Install app locally
`bundle && bundle exec rake test:setup`
Activate cache 
`bundle exec rails dev:cache` (you should have message "Development mode is now being cached.", if not rerun command)
Run application and navigate to the PP show view, highlighted proposals should have a footer with button `view proposal`.
Note the proposals presents in show view, then navigate to proposals index view and search for the proposal in index. 
The card should now have a footer with `supports count`

Fix proposals cells caching

---

config/application.rb
lib/extends/controllers/decidim/devise/sessions_controller_extends.rb
spec/controllers/sessions_controller_spec.rb

The goal of this PR is to overload the session controller to make sure the first login AH is not shown to the user on his first login on the platform.

Skip first login AH

---

config/application.rb
lib/extends/controllers/decidim/budgets/projects_controller_extends.rb
spec/system/sorting_projects_spec.rb

Hello ! I'm submitting to you this Pull request to fix the ordering of budgets' projects by most votes.
Before this PR, we had a bug where our projects weren't well sorted because we had too many projects to sort and so it just didn't work properly, so by now, we just extend a new function that will correct this feature and make sure everything is sorted before we print it and so avoid in the future to have the same issue.
One important point is that we needed to import our extend directly in our application.rb because if we did it in the file that was intended to welcome our extends, Decidim Awesome ends up crashing our app. 
This pull request is linked to this notion card and fixes it :  [Most Votes Issue](https://www.notion.so/opensourcepolitics/bd4bf860eab94f9daca7da803f09e3b2?v=90abe7 …

Fix - Order by Most Votes

---

Gemfile
Gemfile.lock
app/cells/decidim/proposals/proposal_m_cell.rb

I18n translations changed with Term Customizer does not invalidate the cache_key for proposal cells.
Add I18n translation for state in the proposal cache_key
🚨 Ensure it does not invalidate fix for #16

fix: Caching proposal state I18n translation

---

config/storage.yml

Force the object storage URL to be like :  
`https://<endpoint>/<bucket>/...`
instead of  
`https://<bucket>.<endpoint>/...`

Fix Active Storage path style for scaleway object storage

---

app/views/decidim/shared/_extended_navigation_bar.html.erb
app/views/layouts/decidim/_process_header_steps.html.erb
config/i18n-tasks.yml

Overrides `app/views/layouts/decidim/_process_header_steps.html.erb` for displaying CTAs buttons on mobile. It removes class `show-for-medium`
Do not expand the menu bar when on mobile
- Related to #?
- Fixes #?
- [Notion card](https://www.notion.so/opensourcepolitics/Lyon-Faire-appara-tre-les-boutons-d-action-en-version-mobile-2a562468d1c9430da77d38fe43961e3b?pvs=4)

fix: show cta button on process view

---

Gemfile
Gemfile.lock
config/environments/development.rb
config/routes.rb

When custom state contains a special char like : `'`, it is transformed into `&#39;` in email subject for state changed event. In the email body char are well interpreted.
- Related to https://github.com/alecslupu-pfa/decidim-module-custom_proposal_states/pull/35
- [Notion card](https://www.notion.so/opensourcepolitics/Lyon-Email-char-encoding-in-subject-f30fee2e822b4e26b4d690afb31670e8?pvs=4)
*Describe the best way to test or validate your PR.*
Example:
* Log in as admin
* Change event frequency to real_time
* Create proposal
* Change custom state
* See email

fix: custom proposal states emails

---

Gemfile
Gemfile.lock
README.md
db/migrate/20240610143056_create_paper_ballot_results.decidim_budgets_paper_ballots.rb
db/schema.rb

- Related to #?
- Fixes #?
- [Notion card]()
*Describe the best way to test or validate your PR.*
Example:
* Log in as admin
* Access Backoffice
* Go to organization settings
* See ...
*Please add screenshots of the changes you're proposing if related to the UI*

feat: Module paper ballots

---

app/views/decidim/budgets/admin/projects/index.html.erb
config/i18n-tasks.yml

Add budgets importer dropdown option in the budgets projects index page
- [Notion card](https://www.notion.so/opensourcepolitics/Lyon-Dev-Probl-me-avec-l-ajout-du-Budget-importer-396cc7ae97cd40c9899dfe52698002f7?pvs=4)

fix: Add budgets importer dropdown in BO

---

config/locales/decidim-budgets_paper_ballots/fr.yml

The french translation keys are missing with the paper_ballot module
- [Notion card](https://www.notion.so/opensourcepolitics/Lyon-Dev-Cl-de-trad-manquant-avec-le-module-paper-ballot-f63d3d548ef1421089e73873364c020f?pvs=4)
As admin, Go to a process budget

fix:add french translation key for paper_ballot module

---

Gemfile.lock

🎩 Description
Fix the unexpected appearance of "budgetimporter" in the list components dropdown 
📌 Related Issues
[Notion card](/opensourcepolitics/Budget-Importer-Le-budget-importer-est-pr-sent-dans-la-liste-des-fonctionnalit-s-des-Process-et-As-6e50351e7a904b4e82945a220b9f5368?pvs=4)
Testing
1. As admin go to dashboard
2. Go to a process 
3. Go to components
4. Click on "add component"
5. You can see that budget_importer isn't displayed anymore 🎉
9. 
10. Option: If you want to confirm that budget importer still works, you can follow this steps => https://github.com/OpenSourcePolitics/decidim-lyon/pull/84
📷 Screenshots

fix:budget_importer

---

Gemfile
Gemfile.lock
spec/wicked_pdf_spec.rb

Downgrading wicked pdf to fix the issue of exporting surveys
- [[LYON] Downgrade Wicked_pdf signature](https://www.notion.so/opensourcepolitics/LYON-Downgrade-Wicked_pdf-signature-47f773fb68f44b58a44b3ec6d5dae87e?pvs=4)
*Describe the best way to test or validate your PR.*
Example:
* Log in as admin
* Access Backoffice
* Go to a processes settings
* Enable a survey
* Fill and submit the survey
* Go back to the back office
* Exports the answers
* Check if it appears on the letter opener
* If it doesn't go to the sidekiq interface `/sidekiq`
* Login as system 
* Make sure it is enqueued and not failed
*Please add screenshots of the changes you're proposing if related to the UI*

fix: Downgrade wicked pdf

---

Gemfile.lock

🎩 Description
Bump ptp : Budget Booth, the vote confirmation is neither notified or sent by email.
📌 Related Issues
[Notion card](https://www.notion.so/opensourcepolitics/Lyon-Dev-Budget-Booth-la-confirmation-du-vote-n-est-pas-notifi-e-ni-envoy-e-par-mail-9f649dc61dd14ac0b58ae3693231f4ca?pvs=4)
Testing
**Dashboard**
1. As an admin, go to a process.
2. Go to the budget setting (in components, click on the settings icon).
3. Click on **“Vote in one: allows participants to vote in any budget, but only in one.”** and **“Voting enabled.”**
4. 
5. Update.
**Front-end**
1. Go to the process you changed.
2. Go to budgets.
3. Start voting (enter the budget booth).
4. Vote.
5. Go to your notifications and confirm that you received one about your vote.
6. Go to …

bump fix notifications and mails send after voting

---

config/i18n-tasks.yml
config/locales/en.yml
config/locales/fr.yml

Addition of missing translations keys for the dropdown export button in admin proposals index.
- [Notion card](https://www.notion.so/opensourcepolitics/bd4bf860eab94f9daca7da803f09e3b2?v=c96df65755dd403d95e86f82d7749709&p=fff5d39996a78063a0a8c6a37ff033d8&pm=c)
1. As an admin, go to a process
2. Got to proposals
3. Click on "Export" button and see that you have the needed translations fo the different types of exports.
4. Change the language for french and see that you have the needed translations

Fix export dropdown in admin proposals index

---

Gemfile.lock

Bump of updated decidim-module-simple_proposal
- [Notion card](https://www.notion.so/opensourcepolitics/Lyon-DEV-Probl-me-avec-les-secteurs-dans-la-fonctionnalit-budget-non-visible-sur-la-prod-et-no-7499cc6cc01041248a7e3a85b6b4814d)
* As an admin, go to a process and then to budgets
* Click on "Manage projects" of a budget (cf screenshot one)
* Go to the edit of a project which has a scope (cf screenshot two)
* In the edit view, see that the scope is selected (cf screenshot three)

Bump simple proposal to fix selected scope method

---

config/sidekiq.yml

The queue `user_report` is duplicated

fix(sidekiq): duplicate sidekiq queue

---

app/presenters/concerns/decidim/user_presenter_concern.rb
config/application.rb
spec/presenters/decidim/user_presenter_spec.rb

This PR extends the user presenter to disable the author tooltip in views
Tooltip example:

fix: Disable author tooltip

---

app/views/decidim/proposals/proposals/index.html.erb
app/views/decidim/proposals/proposals/index.js.erb
config/environments/development.rb
config/i18n-tasks.yml

- This PR removes the proposal map from the proposal component index page. 
- Allow to change Rails log level in development mode
🚨 This PR is temporary to enhance page performances. At the moment, the map is hidden using CSS directly from header snippet.

fix: Remove proposals map from index

---

Gemfile
Gemfile.lock
spec/models/proposal_extra_field_spec.rb

Disable feature Proposal Vote Weight from Decidim Awesome to reduce queries about extra private fields
see:
https://github.com/decidim-ice/decidim-module-decidim_awesome/blob/d3ad84446fa0970a95b1c76e5d2f7e44de4d64a3/app/cells/concerns/decidim/decidim_awesome/proposal_m_cell_override.rb#L12
https://github.com/decidim-ice/decidim-module-decidim_awesome/blob/d3ad84446fa0970a95b1c76e5d2f7e44de4d64a3/lib/decidim/decidim_awesome/engine.rb#L80
🚨 There is no more proposal vote weight feature from Awesome

fix: Remove vote weight feat from awesome

---

config/storage.yml
lib/extends/serializers/proposals/proposals_serializer_extends.rb

- Fix Active Storage
- Update Separator

fix: Separator in attachment urls

---

.env-example
Gemfile
Gemfile.lock
app/services/decidim/sms_gateway_service.rb
app/views/decidim/account/show.html.erb
config/application.rb
config/i18n-tasks.yml
config/initializers/decidim.rb
config/initializers/half_signup.rb
config/locales/en.yml
config/locales/fr.yml
config/secrets.yml
db/migrate/20241219100637_create_auth_settings.decidim_half_signup.rb
db/migrate/20241219100638_add_phone_number_to_decidim_user.decidim_half_signup.rb
db/schema.rb
lib/extends/models/decidim/user_extends.rb

This PR adds the "Half Signup" feature through middleware, allowing users to create a "partial" account using their email or phone number. This ensures easier voting while verifying user identity for each voting action. Additionally, untested overrides or not matching the last versions of it, such as User model extensions and the `account/show.erb` view, have been added to align with Decidim's `release/0.27-stable` branch, incorporating "Half Signup" adjustments like phone number editing.
- [Ajout du module Half sign up ](https://www.notion.so/opensourcepolitics/Decidim-app-2-2-Ajout-module-half-sign-up-acdc92c247fa42db8cd4ca2afdad7e50?pvs=4)
- You'll need to add multiple environment variables if you want to test that the gateway works correctly
``` …
```

feat: Addition of Half Signup

---

lib/extends/models/decidim/user_extends.rb

The notifications settings page does not display correctly
- [Odoo](https://opensourcepolitics.odoo.com/odoo/action-465/140/tasks/4095)
1. Log in as admin or user
2. Go to your account and click on 'notifications settings'
3. See that you have the notifications settings page is displayed correctly 🎉

Fix notifications settings page

---

config/initializers/decidim.rb

It changes the way we handle dynamic map loading in the Decidim-App, as we were exceeding the daily quota by loading tiles through the "Here" service. We decided to use the OpenStreetMap service instead, which imposes fewer restrictions on API calls.
It also fixes the issue where "static" maps were not displaying due to a configuration setting that was enforcing the use of the "HERE" service. This was preventing map generation when the daily quota was exceeded.
- [🐛 BUG Map (proposals geo) not showing](https://opensourcepolitics.odoo.com/odoo/all-tasks/4133)
- [Backport dcd-app fix: Change the dynamic maps loading using OpenStreetMap #685](https://github.com/OpenSourcePolitics/decidim-app/pull/685)
* Access Homepage
* Make sure Decidim Awesome Map and Homepage Interactive Map are loading …

backport: Remove config entry to enforce OSM default over HERE

---

Gemfile.lock

Bump half signup to fix last issues regarding the error management
- [Lyon - Bump module half sign up #740](https://github.com/OpenSourcePolitics/decidim-app/issues/740)
1. **Log in** as an admin user.  
2. **Open the Backoffice**.  
3. Navigate to **Organization Settings** → **Authentication Settings**.  
4. **Enable SMS Authentication**.  
5. Go to a **Participatory Process** and access its **Budgets component**.  
6. Modify the settings to **allow voting on all budgets** (to simplify testing).  
7. Open the **Front-Office**.  
8. **Attempt to vote** using **Half Signup**.  
9. **Confirm** that the voting process works correctly.  
10. **Log in again** and **wait 5 minutes** before entering the verification code.  
11. Verify that a **flash alert** appears …

bump: Half signup to last release

---

config/locales/custom_translations/fr.yml

This PR adds multiple locales that are really static but ensure that they will not suffer the decidim-awesome issues regarding the instability of the cache and the locales
- Fixes #141 
Short configuration
* Login as a user 
* Make sure you have the french locale activated
* Navigate through a PP and search a budgets component
* Make sure when you're going to vote that new translations are applied (you may check which one are changed but you can check the description linked to the starting button to vote)
Long configuration
* Login as an admin
* Go to organization settings
* Enable Half Signup through Authentication Settings SMS method
* Configure a budget in a Participatory Process where you can vote minimum for 3 projects and maximum for 10 (you may need to create new ones)
* Make sure …

feat: Add static locales to avoid decidim-awesome issues

---

.github/workflows/ci_cd.yml
Gemfile.lock

This PR bumps the decidim-module_ptp to its latest commit.
- [Github card](https://github.com/orgs/OpenSourcePolitics/projects/26/views/1?pane=issue&itemId=109081684&issue=OpenSourcePolitics%7Cdecidim-lyon%7C145)
1. To test the PR, go to decidim-lyon develop and update in the gemfile the line for budgets_booth gem like this gem "decidim-budgets_booth", github: "OpenSourcePolitics/decidim-module-ptp", branch: "fix/projects_display_on_map"
2. Bundle install
3. As an admin, go to a process, go to the Budgets component and enable geocoding in the configuration page, and set the project per page to 3
4. Choose a budget with 2 projects.
5. Create 4 new projects with addresses.
6. In FO, go to the projects index view: see that the map is displayed and that the projects displayed on the map match …

feat: bump module ptp

---

Gemfile.lock

🎩 Description
This PR bumps the decidim-module_ptp to its latest commit.
📌 Related Issues
https://github.com/orgs/OpenSourcePolitics/projects/26/views/1?pane=issue&itemId=109081684&issue=OpenSourcePolitics%7Cdecidim-lyon%7C145
To test the PR, go to decidim-lyon develop and update in the gemfile the line for budgets_booth gem like this gem "decidim-budgets_booth", github: "OpenSourcePolitics/decidim-module-ptp", branch: "fix/projects_display_on_map"
Bundle install
As an admin, go to a process, go to the Budgets component and enable geocoding in the configuration page, and set the project per page to 3
Choose a budget with 2 projects.
Create 4 new projects with addresses.
In FO, go to the projects index view: see that the map is displayed and that the projects displayed on the map match the …

bump: module ptp to fix display of projects in map when using filters

---

app/controllers/decidim/budgets/projects_controller.rb
spec/spec_helper.rb
spec/system/explore_projects_spec.rb

This PR keeps the order of projects in projects index view when filtering and then using pagination.
- [Github card](https://github.com/orgs/OpenSourcePolitics/projects/26/views/1?pane=issue&itemId=109437478&issue=OpenSourcePolitics%7Cdecidim-lyon%7C147)
1. In BO, go to a budget and add several projects with 2 different categories
2. On the budget component, change the number of projects per page to 4
3. In FO, go to the projects index view
4. Filter by category and keep in mind the projects displayed on page one
5. Go to page 2 and then go back to page one and see that the projects displayed on page one are the same as before.
6.  Go to the projects index view in another browser, repeat the step 4 and check that the projects displayed are different from the ones displayed in first …

Fix projects list with filters
